# name: Build Docker Images

# on:
#   push:
#     paths:
#       - "src/go/producer/**"

# jobs:
#   build-docker-producer:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v3

#       - name: Build producer
#         run: |
#           docker build -t producer:1.0 -f docker/Dockerfile.producer .
#           docker run --rm producer:1.0