# name: Trigger Repo1 Workflow

# on:
#   workflow_dispatch:

# jobs:
#   trigger-repo1:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Trigger Workflow in Repo1
#         env:
#           REPO1_PAT: ${{ secrets.REPO1_PAT }}
#         run: |
#           curl -X POST \
#             -H "Accept: application/vnd.github+json" \
#             -H "Authorization: token $REPO1_PAT" \
#             https://api.github.com/repos/joindigital/github-action-poc2/dispatches \
#             -d '{"event_type": "trigger-event", "client_payload": {"custom": "data"}}'